import { useApp } from '../context/AppContext'
import { useHistory } from '../hooks/useHistory'
import { useState } from 'react'
import { Scale, Copy, Download, Trash2, AlertTriangle, ArrowRight, Calendar, Users, BookOpen, FileWarning, CheckSquare, FileText, Volume2, Play, Pause, Square } from 'lucide-react'
import jsPDF from 'jspdf'
import { lamejs } from 'lamejs'
import axios from 'axios'
import styles from './ResultPanel.module.css'

// ── Risk badge colours ──────────────────────────────────────────────
function RiskBadge({ level }) {
  const cls = {
    High:   styles.riskHigh,
    Medium: styles.riskMed,
    Low:    styles.riskLow,
  }[level] || styles.riskLow

  return <span className={`${styles.metaTag} ${cls}`}>Risk: {level}</span>
}

// ── Section wrapper ─────────────────────────────────────────────────
function Section({ icon: Icon, title, children }) {
  return (
    <div className={styles.section}>
      <div className={styles.sectionHead}>
        <Icon size={14} />
        <h3>{title}</h3>
      </div>
      {children}
    </div>
  )
}

// ── Play audio using Web Speech API ───────────────────────────────────────
function playAudio(r) {
  if (!('speechSynthesis' in window)) {
    alert('Speech synthesis is not supported in your browser.')
    return
  }

  // Stop any ongoing speech
  speechSynthesis.cancel()

  const speechText = buildSpeechText(r)

  const utterance = new SpeechSynthesisUtterance(speechText)
  utterance.rate = 0.9
  utterance.pitch = 1
  utterance.volume = 1
  
  // Get available voices and select a good one
  const voices = speechSynthesis.getVoices()
  const preferredVoice = voices.find(voice => 
    voice.lang.includes('en') && (voice.name.includes('Female') || voice.name.includes('Woman'))
  ) || voices.find(voice => voice.lang.includes('en')) || voices[0]
  
  if (preferredVoice) {
    utterance.voice = preferredVoice
  }

  speechSynthesis.speak(utterance)
  return utterance
}

// ── Stop audio playback ────────────────────────────────────────────────
function stopAudio() {
  if ('speechSynthesis' in window) {
    speechSynthesis.cancel()
  }
}

// ── Build speech text for audio ───────────────────────────────────────────
function buildSpeechText(r) {
  let speechText = `LexBrief Legal Analysis. Document Type: ${r.document_type || 'Unknown'}. Risk Level: ${r.risk_level || 'Unknown'}. `
  
  if (r.executive_summary) {
    speechText += `Executive Summary: ${r.executive_summary}. `
  }

  if (r.parties?.length) {
    speechText += `Parties involved: `
    r.parties.forEach(p => {
      speechText += `${p.role}: ${p.name}. `
    })
  }

  if (r.key_points?.length) {
    speechText += `Key points: `
    r.key_points.forEach((p, i) => {
      speechText += `${i + 1}. ${p}. `
    })
  }

  if (r.obligations?.length) {
    speechText += `Obligations and duties: `
    r.obligations.forEach((o, i) => {
      speechText += `${i + 1}. ${o}. `
    })
  }

  if (r.risks?.length) {
    speechText += `Risk flags: `
    r.risks.forEach((risk, i) => {
      speechText += `${i + 1}. ${risk}. `
    })
  }

  if (r.important_dates?.length) {
    speechText += `Important dates: `
    r.important_dates.forEach(d => {
      speechText += `${d.label}: ${d.value}. `
    })
  }

  speechText += 'Generated by LexBrief AI Legal Summarizer.'
  return speechText
}

// ── Build PDF export ─────────────────────────────────────────────────
function buildPDF(r) {
  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20
  const lineHeight = 7
  let y = margin

  // Helper function to clean text for PDF
  function cleanText(text) {
    return text
      .replace(/[!"'()*<>[\]^_`{|}~]/g, '') // Remove problematic special characters
      .replace(/[\u2018\u2019]/g, "'") // Replace smart quotes
      .replace(/[\u201C\u201D]/g, '"') // Replace smart double quotes
      .replace(/[\u2013\u2014]/g, '-') // Replace en/em dashes
      .replace(/\s+/g, ' ') // Replace multiple spaces with single space
      .trim()
  }

  // Helper function to add text with word wrap
  function addText(text, fontSize = 11, fontStyle = 'normal') {
    pdf.setFontSize(fontSize)
    pdf.setFont('helvetica', fontStyle)
    const cleanedText = cleanText(text)
    const lines = pdf.splitTextToSize(cleanedText, pageWidth - 2 * margin)
    
    // Check if we need a new page
    if (y + lines.length * lineHeight > pdf.internal.pageSize.getHeight() - margin) {
      pdf.addPage()
      y = margin
    }
    
    pdf.text(lines, margin, y)
    y += lines.length * lineHeight + 3
    return y
  }

  // Header
  pdf.setFontSize(20)
  pdf.setFont('helvetica', 'bold')
  pdf.text('LEXBRIEF LEGAL ANALYSIS', margin, y)
  y += 15

  // Meta information
  pdf.setFontSize(11)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`Document Type: ${r.document_type || 'Unknown'}`, margin, y)
  y += lineHeight
  pdf.text(`Risk Level: ${r.risk_level || 'Unknown'}`, margin, y)
  y += lineHeight
  pdf.text(`Word Count: ${(r.word_count || 0).toLocaleString()}`, margin, y)
  y += lineHeight
  pdf.text(`Generated: ${new Date().toLocaleString()}`, margin, y)
  y += 15

  // Executive Summary
  if (r.executive_summary) {
    y = addText('EXECUTIVE SUMMARY', 14, 'bold')
    y = addText(r.executive_summary)
    y += 5
  }

  // Parties
  if (r.parties?.length) {
    y = addText('PARTIES INVOLVED', 14, 'bold')
    r.parties.forEach(p => {
      y = addText(`${p.role}: ${p.name}`)
    })
    y += 5
  }

  // Key Points
  if (r.key_points?.length) {
    y = addText('KEY CLAUSES & POINTS', 14, 'bold')
    r.key_points.forEach(p => {
      y = addText(`- ${p}`)
    })
    y += 5
  }

  // Obligations
  if (r.obligations?.length) {
    y = addText('OBLIGATIONS & DUTIES', 14, 'bold')
    r.obligations.forEach(o => {
      y = addText(`- ${o}`)
    })
    y += 5
  }

  // Risks
  if (r.risks?.length) {
    y = addText('RISK FLAGS', 14, 'bold')
    r.risks.forEach(risk => {
      y = addText(`- ${risk}`)
    })
    y += 5
  }

  // Important Dates
  if (r.important_dates?.length) {
    y = addText('IMPORTANT DATES', 14, 'bold')
    r.important_dates.forEach(d => {
      y = addText(`${d.label}: ${d.value}`)
    })
  }

  // Footer
  pdf.setFontSize(9)
  pdf.setFont('helvetica', 'italic')
  pdf.text('— Generated by LexBrief AI Legal Summarizer —', margin, pdf.internal.pageSize.getHeight() - 10)

  return pdf
}

// ── Build plain-text export ─────────────────────────────────────────
function buildPlainText(r) {
  let out = `LEXBRIEF — LEGAL DOCUMENT ANALYSIS\n${'='.repeat(42)}\n`
  out += `Document Type : ${r.document_type || 'Unknown'}\n`
  out += `Risk Level    : ${r.risk_level || 'Unknown'}\n`
  out += `Word Count    : ${(r.word_count || 0).toLocaleString()}\n`
  out += `Generated     : ${new Date().toLocaleString()}\n\n`

  if (r.executive_summary)
    out += `EXECUTIVE SUMMARY\n${r.executive_summary}\n\n`

  if (r.parties?.length) {
    out += `PARTIES INVOLVED\n`
    r.parties.forEach(p => { out += `  ${p.role}: ${p.name}\n` })
    out += '\n'
  }
  if (r.key_points?.length) {
    out += `KEY CLAUSES & POINTS\n`
    r.key_points.forEach(p => { out += `  • ${p}\n` })
    out += '\n'
  }
  if (r.obligations?.length) {
    out += `OBLIGATIONS & DUTIES\n`
    r.obligations.forEach(o => { out += `  → ${o}\n` })
    out += '\n'
  }
  if (r.risks?.length) {
    out += `RISK FLAGS\n`
    r.risks.forEach(r2 => { out += `  ⚠ ${r2}\n` })
    out += '\n'
  }
  if (r.important_dates?.length) {
    out += `IMPORTANT DATES\n`
    r.important_dates.forEach(d => { out += `  ${d.label}: ${d.value}\n` })
    out += '\n'
  }
  out += '— Generated by LexBrief AI Legal Summarizer —'
  return out
}

// ── Main component ──────────────────────────────────────────────────
export default function ResultPanel() {
  const { result, setResult, showToast } = useApp()
  const { } = useHistory()
  const [isPlaying, setIsPlaying] = useState(false)
  const [audioProgress, setAudioProgress] = useState(0)
  const [audioDuration, setAudioDuration] = useState(0)

  function handleCopy() {
    if (!result) return
    navigator.clipboard.writeText(buildPlainText(result))
      .then(() => alert('Summary copied to clipboard!'))
  }

  function handlePlayAudio() {
    if (!result) return
    const utterance = playAudio(result)
    setIsPlaying(true)
    setAudioProgress(0)
    showToast('🔊 Playing audio summary...')
    
    // Estimate duration based on text length (average reading speed: 150 words per minute)
    const speechText = buildSpeechText(result)
    const wordCount = speechText.split(/\s+/).length
    const estimatedDuration = (wordCount / 150) * 60 // in seconds
    setAudioDuration(estimatedDuration)
    
    // Set up event listener to know when speech ends
    utterance.onend = () => {
      setIsPlaying(false)
      setAudioProgress(100)
    }
    
    // Track progress using interval
    const progressInterval = setInterval(() => {
      setAudioProgress(prev => {
        if (prev >= 100) {
          clearInterval(progressInterval)
          return 100
        }
        return prev + (100 / (estimatedDuration * 10)) // Update every 100ms
      })
    }, 100)
    
    utterance.onend = () => {
      clearInterval(progressInterval)
      setIsPlaying(false)
      setAudioProgress(100)
    }
  }

  function handleStopAudio() {
    stopAudio()
    setIsPlaying(false)
    showToast('⏹ Audio stopped')
  }

  async function handleDownloadMP3() {
    if (!result) return
    
    try {
      showToast('Generating audio file...')
      const audioBlob = await generateAudioFile(result)
      
      const a = document.createElement('a')
      a.href = URL.createObjectURL(audioBlob)
      a.download = `legal-summary-${Date.now()}.webm`
      a.click()
      URL.revokeObjectURL(a.href)
      
      showToast('✓ Audio file downloaded (WebM format)')
    } catch (error) {
      console.error('Audio generation error:', error)
      showToast('Audio generation failed. Please try again.', 5000)
    }
  }

  // ── Generate real audio file using MediaRecorder API ───────────────────────
  async function generateAudioFile(result) {
    return new Promise((resolve, reject) => {
      if (!('speechSynthesis' in window) || !('MediaRecorder' in window)) {
        reject(new Error('Speech synthesis or MediaRecorder not supported'))
        return
      }

      const speechText = buildSpeechText(result)
      
      // Create audio context for capturing
      const audioContext = new (window.AudioContext || window.webkitAudioContext)()
      const mediaStreamDestination = audioContext.createMediaStreamDestination()
      
      // Create script processor to capture speech synthesis
      const scriptProcessor = audioContext.createScriptProcessor(4096, 1, 1)
      scriptProcessor.connect(mediaStreamDestination)
      
      // Set up MediaRecorder
      const mediaRecorder = new MediaRecorder(mediaStreamDestination.stream)
      const audioChunks = []
      
      mediaRecorder.ondataavailable = (event) => {
        audioChunks.push(event.data)
      }
      
      mediaRecorder.onstop = () => {
        const audioBlob = new Blob(audioChunks, { type: 'audio/webm' })
        resolve(audioBlob)
        cleanup()
      }
      
      const cleanup = () => {
        scriptProcessor.disconnect()
        audioContext.close()
      }
      
      // Start recording
      mediaRecorder.start()
      
      // Create and speak utterance
      const utterance = new SpeechSynthesisUtterance(speechText)
      utterance.rate = 0.9
      utterance.pitch = 1
      utterance.volume = 1
      
      // Get available voices and select a good one
      const voices = speechSynthesis.getVoices()
      const preferredVoice = voices.find(voice => 
        voice.lang.includes('en') && (voice.name.includes('Female') || voice.name.includes('Woman'))
      ) || voices.find(voice => voice.lang.includes('en')) || voices[0]
      
      if (preferredVoice) {
        utterance.voice = preferredVoice
      }
      
      utterance.onend = () => {
        setTimeout(() => {
          mediaRecorder.stop()
        }, 500) // Small delay to ensure all audio is captured
      }
      
      utterance.onerror = (error) => {
        cleanup()
        reject(error)
      }
      
      // Start speaking
      speechSynthesis.speak(utterance)
      
      // Timeout fallback
      setTimeout(() => {
        if (mediaRecorder.state === 'recording') {
          mediaRecorder.stop()
        }
      }, 30000) // 30 second timeout
    })
  }

  function handleDownloadPDF() {
    if (!result) return
    const pdf = buildPDF(result)
    pdf.save(`legal-summary-${Date.now()}.pdf`)
  }

  function handleDownloadTXT() {
    if (!result) return
    const blob = new Blob([buildPlainText(result)], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `legal-summary-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  function handleClear() {
    setResult(null)
  }

  return (
    <div className={styles.panel}>
      <div className={styles.header}>
        <h2>Analysis Result</h2>
        <span className={styles.step}>Step 03</span>
      </div>
      <div className={styles.body}>
        {/* Empty state */}
        {!result && (
          <div className={styles.empty}>
            <Scale size={48} strokeWidth={1} className={styles.emptyIcon} />
            <p>Your legal analysis will appear here.</p>
            <p className={styles.emptySub}>Paste a document and click <strong>Analyze</strong> to begin.</p>
          </div>
        )}

        {/* Result */}
        {result && (
          <div className={styles.result}>
            {/* Meta row */}
            <div className={styles.metaRow}>
              {result.document_type && (
                <span className={`${styles.metaTag} ${styles.metaType}`}>
                  {result.document_type}
                </span>
              )}
              {result.risk_level && <RiskBadge level={result.risk_level} />}
              {result.word_count > 0 && (
                <span className={styles.metaTag}>
                  ~{result.word_count.toLocaleString()} words
                </span>
              )}
              <span className={styles.metaTag}>
                {new Date().toLocaleDateString()}
              </span>
            </div>

            {/* Executive Summary */}
            {result.executive_summary && (
              <Section icon={BookOpen} title="Executive Summary">
                <p className={styles.summaryText}>{result.executive_summary}</p>
              </Section>
            )}

            {/* Parties */}
            {result.parties?.length > 0 && (
              <Section icon={Users} title="Parties Involved">
                <div className={styles.partiesGrid}>
                  {result.parties.map((p, i) => (
                    <div key={i} className={styles.partyCard}>
                      <div className={styles.partyRole}>{p.role}</div>
                      <div className={styles.partyName}>{p.name}</div>
                    </div>
                  ))}
                </div>
              </Section>
            )}

            {/* Key Points */}
            {result.key_points?.length > 0 && (
              <Section icon={CheckSquare} title="Key Clauses & Points">
                <ul className={styles.keyList}>
                  {result.key_points.map((pt, i) => (
                    <li key={i} className={styles.keyItem}>{pt}</li>
                  ))}
                </ul>
              </Section>
            )}

            {/* Obligations */}
            {result.obligations?.length > 0 && (
              <Section icon={ArrowRight} title="Obligations & Duties">
                <ul className={styles.obligationList}>
                  {result.obligations.map((ob, i) => (
                    <li key={i} className={styles.obligationItem}>{ob}</li>
                  ))}
                </ul>
              </Section>
            )}

            {/* Risks */}
            {result.risks?.length > 0 && (
              <Section icon={AlertTriangle} title="Risk Flags">
                <ul className={styles.riskList}>
                  {result.risks.map((r, i) => (
                    <li key={i} className={styles.riskItem}>{r}</li>
                  ))}
                </ul>
              </Section>
            )}

            {/* Dates */}
            {result.important_dates?.length > 0 && (
              <Section icon={Calendar} title="Important Dates & Deadlines">
                <div className={styles.datesGrid}>
                  {result.important_dates.map((d, i) => (
                    <div key={i} className={styles.dateRow}>
                      <span className={styles.dateLabel}>{d.label}</span>
                      <span className={styles.dateVal}>{d.value}</span>
                    </div>
                  ))}
                </div>
              </Section>
            )}

            {/* Action Bar */}
            <div className={styles.actions}>
              <button className={`${styles.btn} ${styles.btnPrimary}`} onClick={handleCopy}>
                <Copy size={13} /> Copy Summary
              </button>
              <button className={styles.btn} onClick={handleDownloadPDF}>
                <FileText size={13} /> Download PDF
              </button>
              <button className={`${styles.btn} ${styles.btnPrimary}`} onClick={handlePlayAudio} disabled={isPlaying}>
                <Play size={13} /> Play Audio
              </button>
              <button className={`${styles.btn} ${isPlaying ? styles.btnDanger : ''}`} onClick={handleStopAudio} disabled={!isPlaying}>
                <Square size={13} /> Stop
              </button>
              <button className={styles.btn} onClick={handleDownloadMP3}>
                <Volume2 size={13} /> Download Audio
              </button>
              <button className={`${styles.btn} ${styles.btnDanger}`} onClick={handleClear}>
                <Trash2 size={13} /> Clear
              </button>
            </div>

            {/* Audio Progress Bar */}
            {isPlaying && (
              <div className={styles.audioProgress}>
                <div className={styles.progressBar}>
                  <div 
                    className={styles.progressFill} 
                    style={{ width: `${audioProgress}%` }}
                  />
                </div>
                <span className={styles.progressText}>
                  {Math.round(audioProgress)}% complete
                </span>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}
